[package]
name = "qclipsing-os"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "qclipsing-os"
path = "kernel/src/main.rs"

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


